import {type TFunction} from 'i18next';

export const CURRENCIES= (t: TFunction) => [
  {
    name: t('expense_add:ui/currency/currency_list/EUR/name'),
    symbol: '€',
    symbolNative: '€',
    decimalDigits: 2,
    rounding: 0,
    code: 'EUR',
    namePlural: t('expense_add:ui/currency/currency_list/EUR/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/USD/name'),
    symbol: '$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    code: 'USD',
    namePlural: t('expense_add:ui/currency/currency_list/USD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/AED/name'),
    symbol: 'AED',
    symbolNative: 'د.إ.‏',
    decimalDigits: 2,
    rounding: 0,
    code: 'AED',
    namePlural: t('expense_add:ui/currency/currency_list/AED/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/AFN/name'),
    symbol: 'Af',
    symbolNative: '؋',
    decimalDigits: 0,
    rounding: 0,
    code: 'AFN',
    namePlural: t('expense_add:ui/currency/currency_list/AFN/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/ALL/name'),
    symbol: 'ALL',
    symbolNative: 'Lek',
    decimalDigits: 0,
    rounding: 0,
    code: 'ALL',
    namePlural: t('expense_add:ui/currency/currency_list/ALL/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/AMD/name'),
    symbol: 'AMD',
    symbolNative: 'դր.',
    decimalDigits: 0,
    rounding: 0,
    code: 'AMD',
    namePlural: t('expense_add:ui/currency/currency_list/AMD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/ARS/name'),
    symbol: 'AR$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    code: 'ARS',
    namePlural: t('expense_add:ui/currency/currency_list/ARS/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/AUD/name'),
    symbol: 'AU$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    code: 'AUD',
    namePlural: t('expense_add:ui/currency/currency_list/AUD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/AZN/name'),
    symbol: 'man.',
    symbolNative: 'ман.',
    decimalDigits: 2,
    rounding: 0,
    code: 'AZN',
    namePlural: t('expense_add:ui/currency/currency_list/AZN/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/BAM/name'),
    symbol: 'KM',
    symbolNative: 'KM',
    decimalDigits: 2,
    rounding: 0,
    code: 'BAM',
    namePlural: t('expense_add:ui/currency/currency_list/BAM/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/BDT/name'),
    symbol: 'Tk',
    symbolNative: '৳',
    decimalDigits: 2,
    rounding: 0,
    code: 'BDT',
    namePlural: t('expense_add:ui/currency/currency_list/BDT/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/BGN/name'),
    symbol: 'BGN',
    symbolNative: 'лв.',
    decimalDigits: 2,
    rounding: 0,
    code: 'BGN',
    namePlural: t('expense_add:ui/currency/currency_list/BGN/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/BHD/name'),
    symbol: 'BD',
    symbolNative: 'د.ب.‏',
    decimalDigits: 3,
    rounding: 0,
    code: 'BHD',
    namePlural: t('expense_add:ui/currency/currency_list/BHD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/BIF/name'),
    symbol: 'FBu',
    symbolNative: 'FBu',
    decimalDigits: 0,
    rounding: 0,
    code: 'BIF',
    namePlural: t('expense_add:ui/currency/currency_list/BIF/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/BND/name'),
    symbol: 'BN$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    code: 'BND',
    namePlural: t('expense_add:ui/currency/currency_list/BND/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/BOB/name'),
    symbol: 'Bs',
    symbolNative: 'Bs',
    decimalDigits: 2,
    rounding: 0,
    code: 'BOB',
    namePlural: t('expense_add:ui/currency/currency_list/BOB/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/BRL/name'),
    symbol: 'R$',
    symbolNative: 'R$',
    decimalDigits: 2,
    rounding: 0,
    code: 'BRL',
    namePlural: t('expense_add:ui/currency/currency_list/BRL/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/BWP/name'),
    symbol: 'BWP',
    symbolNative: 'P',
    decimalDigits: 2,
    rounding: 0,
    code: 'BWP',
    namePlural: t('expense_add:ui/currency/currency_list/BWP/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/BYN/name'),
    symbol: 'Br',
    symbolNative: 'руб.',
    decimalDigits: 2,
    rounding: 0,
    code: 'BYN',
    namePlural: t('expense_add:ui/currency/currency_list/BYN/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/BZD/name'),
    symbol: 'BZ$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    code: 'BZD',
    namePlural: t('expense_add:ui/currency/currency_list/BZD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/CAD/name'),
    symbol: 'CA$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    code: 'CAD',
    namePlural: t('expense_add:ui/currency/currency_list/CAD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/CDF/name'),
    symbol: 'CDF',
    symbolNative: 'FrCD',
    decimalDigits: 2,
    rounding: 0,
    code: 'CDF',
    namePlural: t('expense_add:ui/currency/currency_list/CDF/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/CHF/name'),
    symbol: 'CHF',
    symbolNative: 'CHF',
    decimalDigits: 2,
    rounding: 0.05,
    code: 'CHF',
    namePlural: t('expense_add:ui/currency/currency_list/CHF/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/CLP/name'),
    symbol: 'CL$',
    symbolNative: '$',
    decimalDigits: 0,
    rounding: 0,
    code: 'CLP',
    namePlural: t('expense_add:ui/currency/currency_list/CLP/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/CNY/name'),
    symbol: 'CN¥',
    symbolNative: 'CN¥',
    decimalDigits: 2,
    rounding: 0,
    code: 'CNY',
    namePlural: t('expense_add:ui/currency/currency_list/CNY/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/COP/name'),
    symbol: 'CO$',
    symbolNative: '$',
    decimalDigits: 0,
    rounding: 0,
    code: 'COP',
    namePlural: t('expense_add:ui/currency/currency_list/COP/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/CRC/name'),
    symbol: '₡',
    symbolNative: '₡',
    decimalDigits: 0,
    rounding: 0,
    code: 'CRC',
    namePlural: t('expense_add:ui/currency/currency_list/CRC/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/CVE/name'),
    symbol: 'CV$',
    symbolNative: 'CV$',
    decimalDigits: 2,
    rounding: 0,
    code: 'CVE',
    namePlural: t('expense_add:ui/currency/currency_list/CVE/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/CZK/name'),
    symbol: 'Kč',
    symbolNative: 'Kč',
    decimalDigits: 2,
    rounding: 0,
    code: 'CZK',
    namePlural: t('expense_add:ui/currency/currency_list/CZK/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/DJF/name'),
    symbol: 'Fdj',
    symbolNative: 'Fdj',
    decimalDigits: 0,
    rounding: 0,
    code: 'DJF',
    namePlural: t('expense_add:ui/currency/currency_list/DJF/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/DKK/name'),
    symbol: 'Dkr',
    symbolNative: 'kr',
    decimalDigits: 2,
    rounding: 0,
    code: 'DKK',
    namePlural: t('expense_add:ui/currency/currency_list/DKK/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/DOP/name'),
    symbol: 'RD$',
    symbolNative: 'RD$',
    decimalDigits: 2,
    rounding: 0,
    code: 'DOP',
    namePlural: t('expense_add:ui/currency/currency_list/DOP/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/DZD/name'),
    symbol: 'DA',
    symbolNative: 'د.ج.‏',
    decimalDigits: 2,
    rounding: 0,
    code: 'DZD',
    namePlural: t('expense_add:ui/currency/currency_list/DZD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/EEK/name'),
    symbol: 'Ekr',
    symbolNative: 'kr',
    decimalDigits: 2,
    rounding: 0,
    code: 'EEK',
    namePlural: t('expense_add:ui/currency/currency_list/EEK/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/EGP/name'),
    symbol: 'EGP',
    symbolNative: 'ج.م.‏',
    decimalDigits: 2,
    rounding: 0,
    code: 'EGP',
    namePlural: t('expense_add:ui/currency/currency_list/EGP/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/ERN/name'),
    symbol: 'Nfk',
    symbolNative: 'Nfk',
    decimalDigits: 2,
    rounding: 0,
    code: 'ERN',
    namePlural: t('expense_add:ui/currency/currency_list/ERN/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/ETB/name'),
    symbol: 'Br',
    symbolNative: 'Br',
    decimalDigits: 2,
    rounding: 0,
    code: 'ETB',
    namePlural: t('expense_add:ui/currency/currency_list/ETB/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/GBP/name'),
    symbol: '£',
    symbolNative: '£',
    decimalDigits: 2,
    rounding: 0,
    code: 'GBP',
    namePlural: t('expense_add:ui/currency/currency_list/GBP/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/GEL/name'),
    symbol: 'GEL',
    symbolNative: 'GEL',
    decimalDigits: 2,
    rounding: 0,
    code: 'GEL',
    namePlural: t('expense_add:ui/currency/currency_list/GEL/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/GHS/name'),
    symbol: 'GH₵',
    symbolNative: 'GH₵',
    decimalDigits: 2,
    rounding: 0,
    code: 'GHS',
    namePlural: t('expense_add:ui/currency/currency_list/GHS/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/GNF/name'),
    symbol: 'FG',
    symbolNative: 'FG',
    decimalDigits: 0,
    rounding: 0,
    code: 'GNF',
    namePlural: t('expense_add:ui/currency/currency_list/GNF/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/GTQ/name'),
    symbol: 'GTQ',
    symbolNative: 'Q',
    decimalDigits: 2,
    rounding: 0,
    code: 'GTQ',
    namePlural: t('expense_add:ui/currency/currency_list/GTQ/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/HKD/name'),
    symbol: 'HK$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    code: 'HKD',
    namePlural: t('expense_add:ui/currency/currency_list/HKD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/HNL/name'),
    symbol: 'HNL',
    symbolNative: 'L',
    decimalDigits: 2,
    rounding: 0,
    code: 'HNL',
    namePlural: t('expense_add:ui/currency/currency_list/HNL/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/HRK/name'),
    symbol: 'kn',
    symbolNative: 'kn',
    decimalDigits: 2,
    rounding: 0,
    code: 'HRK',
    namePlural: t('expense_add:ui/currency/currency_list/HRK/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/HUF/name'),
    symbol: 'Ft',
    symbolNative: 'Ft',
    decimalDigits: 0,
    rounding: 0,
    code: 'HUF',
    namePlural: t('expense_add:ui/currency/currency_list/HUF/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/IDR/name'),
    symbol: 'Rp',
    symbolNative: 'Rp',
    decimalDigits: 0,
    rounding: 0,
    code: 'IDR',
    namePlural: t('expense_add:ui/currency/currency_list/IDR/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/ILS/name'),
    symbol: '₪',
    symbolNative: '₪',
    decimalDigits: 2,
    rounding: 0,
    code: 'ILS',
    namePlural: t('expense_add:ui/currency/currency_list/ILS/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/INR/name'),
    symbol: '₹',
    symbolNative: '₹',
    decimalDigits: 2,
    rounding: 0,
    code: 'INR',
    namePlural: t('expense_add:ui/currency/currency_list/INR/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/IQD/name'),
    symbol: 'IQD',
    symbolNative: 'د.ع.‏',
    decimalDigits: 0,
    rounding: 0,
    code: 'IQD',
    namePlural: t('expense_add:ui/currency/currency_list/IQD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/IRR/name'),
    symbol: 'IRR',
    symbolNative: '﷼',
    decimalDigits: 0,
    rounding: 0,
    code: 'IRR',
    namePlural: t('expense_add:ui/currency/currency_list/IRR/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/ISK/name'),
    symbol: 'Ikr',
    symbolNative: 'kr',
    decimalDigits: 0,
    rounding: 0,
    code: 'ISK',
    namePlural: t('expense_add:ui/currency/currency_list/ISK/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/JMD/name'),
    symbol: 'J$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    code: 'JMD',
    namePlural: t('expense_add:ui/currency/currency_list/JMD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/JOD/name'),
    symbol: 'JD',
    symbolNative: 'د.أ.‏',
    decimalDigits: 3,
    rounding: 0,
    code: 'JOD',
    namePlural: t('expense_add:ui/currency/currency_list/JOD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/JPY/name'),
    symbol: '¥',
    symbolNative: '￥',
    decimalDigits: 0,
    rounding: 0,
    code: 'JPY',
    namePlural: t('expense_add:ui/currency/currency_list/JPY/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/KES/name'),
    symbol: 'Ksh',
    symbolNative: 'Ksh',
    decimalDigits: 2,
    rounding: 0,
    code: 'KES',
    namePlural: t('expense_add:ui/currency/currency_list/KES/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/KHR/name'),
    symbol: 'KHR',
    symbolNative: '៛',
    decimalDigits: 2,
    rounding: 0,
    code: 'KHR',
    namePlural: t('expense_add:ui/currency/currency_list/KHR/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/KMF/name'),
    symbol: 'CF',
    symbolNative: 'FC',
    decimalDigits: 0,
    rounding: 0,
    code: 'KMF',
    namePlural: t('expense_add:ui/currency/currency_list/KMF/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/KRW/name'),
    symbol: '₩',
    symbolNative: '₩',
    decimalDigits: 0,
    rounding: 0,
    code: 'KRW',
    namePlural: t('expense_add:ui/currency/currency_list/KRW/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/KWD/name'),
    symbol: 'KD',
    symbolNative: 'د.ك.‏',
    decimalDigits: 3,
    rounding: 0,
    code: 'KWD',
    namePlural: t('expense_add:ui/currency/currency_list/KWD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/KZT/name'),
    symbol: 'KZT',
    symbolNative: 'тңг.',
    decimalDigits: 2,
    rounding: 0,
    code: 'KZT',
    namePlural: t('expense_add:ui/currency/currency_list/KZT/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/LAK/name'),
    symbol: 'LAK',
    symbolNative: '₭',
    decimalDigits: 0,
    rounding: 0,
    code: 'LAK',
    namePlural: t('expense_add:ui/currency/currency_list/LAK/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/LBP/name'),
    symbol: 'LB£',
    symbolNative: 'ل.ل.‏',
    decimalDigits: 0,
    rounding: 0,
    code: 'LBP',
    namePlural: t('expense_add:ui/currency/currency_list/LBP/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/LKR/name'),
    symbol: 'SLRs',
    symbolNative: 'SL Re',
    decimalDigits: 2,
    rounding: 0,
    code: 'LKR',
    namePlural: t('expense_add:ui/currency/currency_list/LKR/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/LTL/name'),
    symbol: 'Lt',
    symbolNative: 'Lt',
    decimalDigits: 2,
    rounding: 0,
    code: 'LTL',
    namePlural: t('expense_add:ui/currency/currency_list/LTL/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/LVL/name'),
    symbol: 'Ls',
    symbolNative: 'Ls',
    decimalDigits: 2,
    rounding: 0,
    code: 'LVL',
    namePlural: t('expense_add:ui/currency/currency_list/LVL/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/LYD/name'),
    symbol: 'LD',
    symbolNative: 'د.ل.‏',
    decimalDigits: 3,
    rounding: 0,
    code: 'LYD',
    namePlural: t('expense_add:ui/currency/currency_list/LYD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/MAD/name'),
    symbol: 'MAD',
    symbolNative: 'د.م.‏',
    decimalDigits: 2,
    rounding: 0,
    code: 'MAD',
    namePlural: t('expense_add:ui/currency/currency_list/MAD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/MDL/name'),
    symbol: 'MDL',
    symbolNative: 'MDL',
    decimalDigits: 2,
    rounding: 0,
    code: 'MDL',
    namePlural: t('expense_add:ui/currency/currency_list/MDL/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/MGA/name'),
    symbol: 'MGA',
    symbolNative: 'MGA',
    decimalDigits: 0,
    rounding: 0,
    code: 'MGA',
    namePlural: t('expense_add:ui/currency/currency_list/MGA/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/MKD/name'),
    symbol: 'MKD',
    symbolNative: 'MKD',
    decimalDigits: 2,
    rounding: 0,
    code: 'MKD',
    namePlural: t('expense_add:ui/currency/currency_list/MKD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/MMK/name'),
    symbol: 'MMK',
    symbolNative: 'K',
    decimalDigits: 0,
    rounding: 0,
    code: 'MMK',
    namePlural: t('expense_add:ui/currency/currency_list/MMK/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/MNT/name'),
    symbol: 'MNT',
    symbolNative: '₮',
    decimalDigits: 2,
    rounding: 0,
    code: 'MNT',
    namePlural: t('expense_add:ui/currency/currency_list/MNT/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/MOP/name'),
    symbol: 'MOP$',
    symbolNative: 'MOP$',
    decimalDigits: 2,
    rounding: 0,
    code: 'MOP',
    namePlural: t('expense_add:ui/currency/currency_list/MOP/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/MUR/name'),
    symbol: 'MURs',
    symbolNative: 'MURs',
    decimalDigits: 0,
    rounding: 0,
    code: 'MUR',
    namePlural: t('expense_add:ui/currency/currency_list/MUR/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/MXN/name'),
    symbol: 'MX$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    code: 'MXN',
    namePlural: t('expense_add:ui/currency/currency_list/MXN/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/MYR/name'),
    symbol: 'RM',
    symbolNative: 'RM',
    decimalDigits: 2,
    rounding: 0,
    code: 'MYR',
    namePlural: t('expense_add:ui/currency/currency_list/MYR/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/MZN/name'),
    symbol: 'MTn',
    symbolNative: 'MTn',
    decimalDigits: 2,
    rounding: 0,
    code: 'MZN',
    namePlural: t('expense_add:ui/currency/currency_list/MZN/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/NAD/name'),
    symbol: 'N$',
    symbolNative: 'N$',
    decimalDigits: 2,
    rounding: 0,
    code: 'NAD',
    namePlural: t('expense_add:ui/currency/currency_list/NAD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/NGN/name'),
    symbol: '₦',
    symbolNative: '₦',
    decimalDigits: 2,
    rounding: 0,
    code: 'NGN',
    namePlural: t('expense_add:ui/currency/currency_list/NGN/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/NIO/name'),
    symbol: 'C$',
    symbolNative: 'C$',
    decimalDigits: 2,
    rounding: 0,
    code: 'NIO',
    namePlural: t('expense_add:ui/currency/currency_list/NIO/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/NOK/name'),
    symbol: 'Nkr',
    symbolNative: 'kr',
    decimalDigits: 2,
    rounding: 0,
    code: 'NOK',
    namePlural: t('expense_add:ui/currency/currency_list/NOK/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/NPR/name'),
    symbol: 'NPRs',
    symbolNative: 'नेरू',
    decimalDigits: 2,
    rounding: 0,
    code: 'NPR',
    namePlural: t('expense_add:ui/currency/currency_list/NPR/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/NZD/name'),
    symbol: 'NZ$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    code: 'NZD',
    namePlural: t('expense_add:ui/currency/currency_list/NZD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/OMR/name'),
    symbol: 'OMR',
    symbolNative: 'ر.ع.‏',
    decimalDigits: 3,
    rounding: 0,
    code: 'OMR',
    namePlural: t('expense_add:ui/currency/currency_list/OMR/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/PAB/name'),
    symbol: 'B/.',
    symbolNative: 'B/.',
    decimalDigits: 2,
    rounding: 0,
    code: 'PAB',
    namePlural: t('expense_add:ui/currency/currency_list/PAB/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/PEN/name'),
    symbol: 'S/.',
    symbolNative: 'S/.',
    decimalDigits: 2,
    rounding: 0,
    code: 'PEN',
    namePlural: t('expense_add:ui/currency/currency_list/PEN/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/PGK/name'),
    symbol: 'PGK',
    symbolNative: 'PGK',
    decimalDigits: 2,
    rounding: 0,
    code: 'PGK',
    namePlural: t('expense_add:ui/currency/currency_list/PGK/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/PHP/name'),
    symbol: '₱',
    symbolNative: '₱',
    decimalDigits: 2,
    rounding: 0,
    code: 'PHP',
    namePlural: t('expense_add:ui/currency/currency_list/PHP/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/PKR/name'),
    symbol: 'PKRs',
    symbolNative: '₨',
    decimalDigits: 0,
    rounding: 0,
    code: 'PKR',
    namePlural: t('expense_add:ui/currency/currency_list/PKR/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/PLN/name'),
    symbol: 'zł',
    symbolNative: 'zł',
    decimalDigits: 2,
    rounding: 0,
    code: 'PLN',
    namePlural: t('expense_add:ui/currency/currency_list/PLN/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/PYG/name'),
    symbol: '₲',
    symbolNative: '₲',
    decimalDigits: 0,
    rounding: 0,
    code: 'PYG',
    namePlural: t('expense_add:ui/currency/currency_list/PYG/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/QAR/name'),
    symbol: 'QR',
    symbolNative: 'ر.ق.‏',
    decimalDigits: 2,
    rounding: 0,
    code: 'QAR',
    namePlural: t('expense_add:ui/currency/currency_list/QAR/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/RON/name'),
    symbol: 'RON',
    symbolNative: 'RON',
    decimalDigits: 2,
    rounding: 0,
    code: 'RON',
    namePlural: t('expense_add:ui/currency/currency_list/RON/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/RSD/name'),
    symbol: 'din.',
    symbolNative: 'дин.',
    decimalDigits: 0,
    rounding: 0,
    code: 'RSD',
    namePlural: t('expense_add:ui/currency/currency_list/RSD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/RUB/name'),
    symbol: 'RUB',
    symbolNative: '₽.',
    decimalDigits: 2,
    rounding: 0,
    code: 'RUB',
    namePlural: t('expense_add:ui/currency/currency_list/RUB/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/RWF/name'),
    symbol: 'RWF',
    symbolNative: 'FR',
    decimalDigits: 0,
    rounding: 0,
    code: 'RWF',
    namePlural: t('expense_add:ui/currency/currency_list/RWF/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/SAR/name'),
    symbol: 'SR',
    symbolNative: 'ر.س.‏',
    decimalDigits: 2,
    rounding: 0,
    code: 'SAR',
    namePlural: t('expense_add:ui/currency/currency_list/SAR/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/SBD/name'),
    symbol: 'SBD',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    code: 'SBD',
    namePlural: t('expense_add:ui/currency/currency_list/SBD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/SCR/name'),
    symbol: 'SCR',
    symbolNative: 'SCR',
    decimalDigits: 2,
    rounding: 0,
    code: 'SCR',
    namePlural: t('expense_add:ui/currency/currency_list/SCR/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/SDG/name'),
    symbol: 'SDG',
    symbolNative: 'SDG',
    decimalDigits: 2,
    rounding: 0,
    code: 'SDG',
    namePlural: t('expense_add:ui/currency/currency_list/SDG/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/SEK/name'),
    symbol: 'Skr',
    symbolNative: 'kr',
    decimalDigits: 2,
    rounding: 0,
    code: 'SEK',
    namePlural: t('expense_add:ui/currency/currency_list/SEK/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/SGD/name'),
    symbol: 'S$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    code: 'SGD',
    namePlural: t('expense_add:ui/currency/currency_list/SGD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/SHP/name'),
    symbol: 'SHP',
    symbolNative: '£',
    decimalDigits: 2,
    rounding: 0,
    code: 'SHP',
    namePlural: t('expense_add:ui/currency/currency_list/SHP/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/SLL/name'),
    symbol: 'SLL',
    symbolNative: 'SLL',
    decimalDigits: 0,
    rounding: 0,
    code: 'SLL',
    namePlural: t('expense_add:ui/currency/currency_list/SLL/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/SOS/name'),
    symbol: 'SOS',
    symbolNative: 'SOS',
    decimalDigits: 0,
    rounding: 0,
    code: 'SOS',
    namePlural: t('expense_add:ui/currency/currency_list/SOS/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/SRD/name'),
    symbol: 'SRD',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    code: 'SRD',
    namePlural: t('expense_add:ui/currency/currency_list/SRD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/SSP/name'),
    symbol: 'SSP',
    symbolNative: 'SSP',
    decimalDigits: 2,
    rounding: 0,
    code: 'SSP',
    namePlural: t('expense_add:ui/currency/currency_list/SSP/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/STD/name'),
    symbol: 'STD',
    symbolNative: 'STD',
    decimalDigits: 2,
    rounding: 0,
    code: 'STD',
    namePlural: t('expense_add:ui/currency/currency_list/STD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/SYP/name'),
    symbol: 'SY£',
    symbolNative: 'ل.س.‏',
    decimalDigits: 0,
    rounding: 0,
    code: 'SYP',
    namePlural: t('expense_add:ui/currency/currency_list/SYP/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/SZL/name'),
    symbol: 'SZL',
    symbolNative: 'SZL',
    decimalDigits: 2,
    rounding: 0,
    code: 'SZL',
    namePlural: t('expense_add:ui/currency/currency_list/SZL/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/THB/name'),
    symbol: '฿',
    symbolNative: '฿',
    decimalDigits: 2,
    rounding: 0,
    code: 'THB',
    namePlural: t('expense_add:ui/currency/currency_list/THB/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/TJS/name'),
    symbol: 'TJS',
    symbolNative: 'TJS',
    decimalDigits: 2,
    rounding: 0,
    code: 'TJS',
    namePlural: t('expense_add:ui/currency/currency_list/TJS/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/TMT/name'),
    symbol: 'TMT',
    symbolNative: 'TMT',
    decimalDigits: 2,
    rounding: 0,
    code: 'TMT',
    namePlural: t('expense_add:ui/currency/currency_list/TMT/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/TND/name'),
    symbol: 'DT',
    symbolNative: 'د.ت.‏',
    decimalDigits: 3,
    rounding: 0,
    code: 'TND',
    namePlural: t('expense_add:ui/currency/currency_list/TND/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/TOP/name'),
    symbol: 'T$',
    symbolNative: 'T$',
    decimalDigits: 2,
    rounding: 0,
    code: 'TOP',
    namePlural: t('expense_add:ui/currency/currency_list/TOP/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/TRY/name'),
    symbol: 'TL',
    symbolNative: 'TL',
    decimalDigits: 2,
    rounding: 0,
    code: 'TRY',
    namePlural: t('expense_add:ui/currency/currency_list/TRY/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/TTD/name'),
    symbol: 'TT$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    code: 'TTD',
    namePlural: t('expense_add:ui/currency/currency_list/TTD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/TWD/name'),
    symbol: 'NT$',
    symbolNative: 'NT$',
    decimalDigits: 2,
    rounding: 0,
    code: 'TWD',
    namePlural: t('expense_add:ui/currency/currency_list/TWD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/TZS/name'),
    symbol: 'TSh',
    symbolNative: 'TSh',
    decimalDigits: 0,
    rounding: 0,
    code: 'TZS',
    namePlural: t('expense_add:ui/currency/currency_list/TZS/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/UAH/name'),
    symbol: '₴',
    symbolNative: '₴',
    decimalDigits: 2,
    rounding: 0,
    code: 'UAH',
    namePlural: t('expense_add:ui/currency/currency_list/UAH/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/UGX/name'),
    symbol: 'USh',
    symbolNative: 'USh',
    decimalDigits: 0,
    rounding: 0,
    code: 'UGX',
    namePlural: t('expense_add:ui/currency/currency_list/UGX/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/UYU/name'),
    symbol: '$U',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    code: 'UYU',
    namePlural: t('expense_add:ui/currency/currency_list/UYU/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/UZS/name'),
    symbol: 'UZS',
    symbolNative: 'UZS',
    decimalDigits: 0,
    rounding: 0,
    code: 'UZS',
    namePlural: t('expense_add:ui/currency/currency_list/UZS/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/VEF/name'),
    symbol: 'Bs.F.',
    symbolNative: 'Bs.F.',
    decimalDigits: 2,
    rounding: 0,
    code: 'VEF',
    namePlural: t('expense_add:ui/currency/currency_list/VEF/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/VND/name'),
    symbol: '₫',
    symbolNative: '₫',
    decimalDigits: 0,
    rounding: 0,
    code: 'VND',
    namePlural: t('expense_add:ui/currency/currency_list/VND/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/VUV/name'),
    symbol: 'VUV',
    symbolNative: 'VUV',
    decimalDigits: 0,
    rounding: 0,
    code: 'VUV',
    namePlural: t('expense_add:ui/currency/currency_list/VUV/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/WST/name'),
    symbol: 'WST',
    symbolNative: 'WST',
    decimalDigits: 2,
    rounding: 0,
    code: 'WST',
    namePlural: t('expense_add:ui/currency/currency_list/WST/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/XAF/name'),
    symbol: 'FCFA',
    symbolNative: 'FCFA',
    decimalDigits: 0,
    rounding: 0,
    code: 'XAF',
    namePlural: t('expense_add:ui/currency/currency_list/XAF/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/XCD/name'),
    symbol: 'XCD',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    code: 'XCD',
    namePlural: t('expense_add:ui/currency/currency_list/XCD/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/XOF/name'),
    symbol: 'CFA',
    symbolNative: 'CFA',
    decimalDigits: 0,
    rounding: 0,
    code: 'XOF',
    namePlural: t('expense_add:ui/currency/currency_list/XOF/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/XPF/name'),
    symbol: 'XPF',
    symbolNative: 'XPF',
    decimalDigits: 0,
    rounding: 0,
    code: 'XPF',
    namePlural: t('expense_add:ui/currency/currency_list/XPF/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/YER/name'),
    symbol: 'YR',
    symbolNative: 'ر.ي.‏',
    decimalDigits: 0,
    rounding: 0,
    code: 'YER',
    namePlural: t('expense_add:ui/currency/currency_list/YER/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/ZAR/name'),
    symbol: 'R',
    symbolNative: 'R',
    decimalDigits: 2,
    rounding: 0,
    code: 'ZAR',
    namePlural: t('expense_add:ui/currency/currency_list/ZAR/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/ZMW/name'),
    symbol: 'ZK',
    symbolNative: 'ZK',
    decimalDigits: 0,
    rounding: 0,
    code: 'ZMW',
    namePlural: t('expense_add:ui/currency/currency_list/ZMW/name_plural'),
  },
  {
    name: t('expense_add:ui/currency/currency_list/ZWL/name'),
    symbol: 'ZWL$',
    symbolNative: 'ZWL$',
    decimalDigits: 0,
    rounding: 0,
    code: 'ZWL',
    namePlural: t('expense_add:ui/currency/currency_list/ZWL/name_plural'),
  }
];