import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import Link from 'next/link';
import { Button } from '~/components/ui/button';
import {
  ArrowRight,
  Ban,
  Banknote,
  FileUp,
  GitFork,
  Globe,
  Group,
  Server,
  Sigma,
  Split,
  Upload,
  Users,
} from 'lucide-react';
import Avatar from 'boring-avatars';

import { api } from '~/utils/api';
import Image from 'next/image';
import { type GetServerSideProps } from 'next';
import { getServerAuthSession } from '~/server/auth';
import { useState } from 'react';
import { Input } from '~/components/ui/input';
import { Separator } from '~/components/ui/separator';
import { motion } from 'framer-motion';

export default function Home() {
  return (
    <>
      <Head>
        <title>SplitPro: Split Expenses with your friends for free</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen">
        <nav className="sticky flex items-center justify-between px-4 py-4 lg:px-10 lg:py-5">
          <div className="flex items-center gap-4">
            <Image src="./logo.svg" alt="logo" className="rounded-full" width={40} height={40} />
            <p className="text-2xl font-bold">SplitPro</p>
          </div>
        </nav>
        <div className="mx-auto mt-20 flex  max-w-5xl items-start gap-8">
          <div>
            <div className="h-[70vh]">
              <h1 className="max-w-3xl text-2xl font-semibold leading-loose text-gray-100  lg:text-5xl lg:leading-[4rem]">
                Split Expenses with your friends for{' '}
                <span className="font-bold text-primary">free</span>.
              </h1>
              <h2 className="mt-5  text-gray-300 lg:mt-5 lg:text-lg">
                SplitPro is an{' '}
                <a
                  className="text-primary underline"
                  href="https://github.com/oss-apps/split-pro"
                  target="_blank"
                >
                  open source
                </a>{' '}
                alternative of SplitWise
              </h2>
              <div className="mt-10 flex flex-col">
                <Link href="/auth/signin">
                  <Button className="flex items-center gap-2">
                    Add Expense <ArrowRight size={15} />{' '}
                  </Button>
                </Link>
              </div>
            </div>
            <div className="flex flex-col gap-12">
              <p className="text-2xl">Features</p>

              <div className="flex gap-8">
                <div className="flex w-1/2 flex-col gap-1">
                  <Users className="h-6 w-6 text-primary" />
                  <p className="text-lg font-medium">Groups and Friends</p>
                  <p className="text-gray-400">
                    Can create multiple users or add balance directly everything will be synced
                  </p>
                </div>

                <div className="flex w-1/2 flex-col gap-1">
                  <Banknote className="h-6 w-6 text-primary" />
                  <p className="text-lg font-medium">Multiple currencies</p>
                  <p className="text-gray-400">
                    Can create multiple users or add balance directly everything will be synced
                  </p>
                </div>
              </div>

              <div className="flex gap-10">
                <div className="flex w-1/2 flex-col gap-1">
                  <Split className="h-6 w-6 text-primary" />
                  <p className="text-lg font-medium">Unequal Split</p>
                  <p className="text-gray-400">
                    Split equally or by shares, percentage or exact amounts.
                  </p>
                </div>

                <div className="flex w-1/2 flex-col gap-1">
                  <Globe className="h-6 w-6 text-primary" />
                  <p className="text-lg font-medium">PWA support</p>
                  <p className="text-gray-400">Add to home screen and use it as an app</p>
                </div>
              </div>

              <div className="flex gap-10">
                <div className="flex w-1/2 flex-col gap-1">
                  <FileUp className="h-6 w-6 text-primary" />
                  <p className="text-lg font-medium">Upload Receipts</p>
                  <p className="text-gray-400">Upload receipts along with the expense</p>
                </div>

                <div className="flex w-1/2 flex-col gap-1">
                  <Sigma className="h-6 w-6 text-primary" />
                  <p className="text-lg font-medium">Total balance</p>
                  <p className="text-gray-400">
                    Consolidated across groups and individual expenses
                  </p>
                </div>
              </div>

              <div className="flex gap-10">
                <div className="flex w-1/2 flex-col gap-1">
                  <Ban className="h-6 w-6 text-primary" />
                  <p className="text-lg font-medium">No ads</p>
                  <p className="text-gray-400">Upload receipts along with the expense</p>
                </div>

                <div className="flex w-1/2 flex-col gap-1">
                  <GitFork className="h-6 w-6 text-primary" />
                  <p className="text-lg font-medium">Open source</p>
                  <p className="text-gray-400">
                    Which makes it hard to become evil. Easy to self host
                  </p>
                </div>
              </div>
            </div>

            <div className="mb-20 mt-24 flex flex-col gap-8">
              <div>
                Built by <a className=" text-primary">KM Koushik</a>
                <p className="text-gray-400">
                  A product of <a className="underline underline-offset-2">ossapps.dev</a>
                </p>
              </div>
              <div className="flex gap-4">
                <a className="text-primary">x</a>
                <a className="text-primary">Github</a>
                <a className="text-primary">ProductHunt</a>
              </div>
            </div>
          </div>
          <div className="sticky top-40 h-[550px] w-[300px] shrink-0 rounded-2xl border"></div>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerAuthSession(context);

  if (session) {
    return {
      redirect: {
        destination: '/balances',
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};
