import { SplitType } from '@prisma/client';

export const dummyUsers = [
  {
    name: 'Alice',
    email: 'alice@example.com',
    currency: 'USD',
  },
  {
    name: 'Bob',
    email: 'bob@example.com',
    currency: 'EUR',
  },
  {
    name: 'Charlie',
    email: 'charlie@example.com',
    currency: 'GBP',
  },
  {
    name: 'Diana',
    email: 'diana@example.com',
    currency: 'JPY',
  },
  {
    name: 'Evan',
    email: 'evan@example.com',
    currency: 'CNY',
  },
];

export const dummyExpenses = [
  {
    name: 'Sushi dinner at Nobu',
    category: 'diningOut',
    amount: 18500,
    currency: 'USD',
    splitType: SplitType.EQUAL,
    paidByIndex: 0,
    participantIndices: [0, 1, 2],
  },
  {
    name: 'Grocery shopping at Whole Foods',
    category: 'groceries',
    amount: 12750,
    currency: 'USD',
    splitType: SplitType.PERCENTAGE,
    paidByIndex: 1,
    participantIndices: [0, 1, 2, 3],
  },
  {
    name: 'Movie tickets for Avengers',
    category: 'movies',
    amount: 4800,
    currency: 'USD',
    splitType: SplitType.EQUAL,
    paidByIndex: 2,
    participantIndices: [1, 2, 3],
  },
  {
    name: 'Uber to airport',
    category: 'taxi',
    amount: 5500,
    currency: 'USD',
    splitType: SplitType.EXACT,
    paidByIndex: 0,
    participantIndices: [0, 1],
  },
  {
    name: 'Hotel booking in Tokyo',
    category: 'travel',
    amount: 450000,
    currency: 'JPY',
    splitType: SplitType.EQUAL,
    paidByIndex: 3,
    participantIndices: [0, 1, 2, 3, 4],
  },
  {
    name: 'Train tickets to Kyoto',
    category: 'train',
    amount: 28000,
    currency: 'JPY',
    splitType: SplitType.SHARE,
    paidByIndex: 4,
    participantIndices: [3, 4],
  },
  {
    name: 'Coffee at Starbucks',
    category: 'diningOut',
    amount: 2200,
    currency: 'USD',
    splitType: SplitType.EQUAL,
    paidByIndex: 1,
    participantIndices: [1, 2],
  },
  {
    name: 'Electricity bill apartment',
    category: 'utilities',
    amount: 8900,
    currency: 'USD',
    splitType: SplitType.ADJUSTMENT,
    paidByIndex: 2,
    participantIndices: [0, 1, 2],
  },
  {
    name: 'Dinner at local ramen shop',
    category: 'diningOut',
    amount: 6800,
    currency: 'JPY',
    splitType: SplitType.EQUAL,
    paidByIndex: 0,
    participantIndices: [0, 3, 4],
  },
  {
    name: 'Gas for rental car',
    category: 'fuel',
    amount: 7200,
    currency: 'USD',
    splitType: SplitType.PERCENTAGE,
    paidByIndex: 3,
    participantIndices: [1, 2, 3],
  },
  {
    name: 'Spotify Premium family plan',
    category: 'music',
    amount: 1599,
    currency: 'USD',
    splitType: SplitType.EQUAL,
    paidByIndex: 4,
    participantIndices: [0, 1, 2, 3, 4],
  },
  {
    name: 'Grocery supplies for party',
    category: 'groceries',
    amount: 15600,
    currency: 'USD',
    splitType: SplitType.EXACT,
    paidByIndex: 0,
    participantIndices: [0, 1, 2, 3],
  },
  {
    name: 'Karaoke night in Shibuya',
    category: 'music',
    amount: 12500,
    currency: 'JPY',
    splitType: SplitType.EQUAL,
    paidByIndex: 1,
    participantIndices: [1, 3, 4],
  },
  {
    name: 'Internet bill for apartment',
    category: 'utilities',
    amount: 6999,
    currency: 'USD',
    splitType: SplitType.SHARE,
    paidByIndex: 2,
    participantIndices: [0, 1, 2],
  },
  {
    name: 'Pizza delivery for game night',
    category: 'diningOut',
    amount: 4500,
    currency: 'USD',
    splitType: SplitType.EQUAL,
    paidByIndex: 3,
    participantIndices: [1, 2, 3, 4],
  },
  {
    name: 'Museum tickets in Tokyo',
    category: 'travel',
    amount: 4200,
    currency: 'JPY',
    splitType: SplitType.PERCENTAGE,
    paidByIndex: 4,
    participantIndices: [0, 3, 4],
  },
  {
    name: 'Parking at downtown mall',
    category: 'parking',
    amount: 1800,
    currency: 'USD',
    splitType: SplitType.EQUAL,
    paidByIndex: 0,
    participantIndices: [0, 1],
  },
  {
    name: 'Phone bill monthly',
    category: 'phone',
    amount: 8500,
    currency: 'USD',
    splitType: SplitType.ADJUSTMENT,
    paidByIndex: 1,
    participantIndices: [1, 2, 3],
  },
  {
    name: 'Brunch at local cafe',
    category: 'diningOut',
    amount: 8900,
    currency: 'USD',
    splitType: SplitType.EXACT,
    paidByIndex: 2,
    participantIndices: [0, 1, 2, 4],
  },
  {
    name: 'Convenience store snacks',
    category: 'groceries',
    amount: 1800,
    currency: 'JPY',
    splitType: SplitType.EQUAL,
    paidByIndex: 3,
    participantIndices: [3, 4],
  },
];
