name: Publish Docker

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the action on'
        default: 'main'
        required: true

jobs:
  build_and_publish_platform_containers:
    name: Build and publish platform containers
    runs-on: ${{ matrix.os }}
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - warp-ubuntu-latest-x64-2x
          - warp-ubuntu-latest-arm64-2x

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set build vars
        env:
          BUILD_PLATFORM: ${{ matrix.os == 'warp-ubuntu-latest-arm64-2x' && 'arm64' || 'amd64' }}
        run: |
          echo "APP_VERSION=$(git name-rev --tags --name-only $(git rev-parse HEAD) | head -n 1 | sed 's/\^0//')" >> $GITHUB_ENV
          echo "GIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "BUILD_PLATFORM=${BUILD_PLATFORM}" >> $GITHUB_ENV

      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-${{ env.BUILD_PLATFORM }}

      - name: Build and push image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ env.BUILD_PLATFORM == 'arm64' && 'linux/arm64' || 'linux/amd64' }}
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }},GIT_SHA=${{ env.GIT_SHA }}

      - name: (noop) platform image pushed
        run: echo "pushed"

  create_and_publish_manifest:
    name: Create and publish manifest
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: build_and_publish_platform_containers
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push GitHub Container Registry manifest
        run: |
          APP_VERSION="$(git name-rev --tags --name-only $(git rev-parse HEAD) | head -n 1 | sed 's/\^0//')"
          GIT_SHA="$(git rev-parse HEAD)"
          if [[ "$APP_VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            CHANNEL=latest
          else
            CHANNEL=next
          fi

          docker manifest create \
            ghcr.io/${{ github.repository }}:$CHANNEL \
            --amend ghcr.io/${{ github.repository }}-amd64:$CHANNEL \
            --amend ghcr.io/${{ github.repository }}-arm64:$CHANNEL \

          docker manifest create \
            ghcr.io/${{ github.repository }}:$GIT_SHA \
            --amend ghcr.io/${{ github.repository }}-amd64:$GIT_SHA \
            --amend ghcr.io/${{ github.repository }}-arm64:$GIT_SHA \

          docker manifest create \
            ghcr.io/${{ github.repository }}:$APP_VERSION \
            --amend ghcr.io/${{ github.repository }}-amd64:$APP_VERSION \
            --amend ghcr.io/${{ github.repository }}-arm64:$APP_VERSION \

          docker manifest push ghcr.io/${{ github.repository }}:$CHANNEL
          docker manifest push ghcr.io/${{ github.repository }}:$GIT_SHA
          docker manifest push ghcr.io/${{ github.repository }}:$APP_VERSION
