
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
"use strict"
const { makeTypedQueryFactory: $mkFactory } = require("../runtime/edge.js")
exports.getAllBalancesForGroup = /*#__PURE__*/ $mkFactory("select \"groupId\", \"userId\" as \"borrowedBy\", \"paidBy\", \"currency\", Coalesce(-1 * sum(\"ExpenseParticipant\".amount),0) as amount FROM \"Expense\"\nJOIN \"ExpenseParticipant\" ON \"ExpenseParticipant\".\"expenseId\" = \"Expense\".id\nWhERE \"groupId\" = $1 AND \"userId\" != \"paidBy\"\nGROUP BY \"userId\", \"paidBy\", \"currency\", \"groupId\"\nORDER By \"currency\"")
