
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
import { makeTypedQueryFactory as $mkFactory } from "../runtime/edge.js"
export const getGroupsWithBalances = /*#__PURE__*/ $mkFactory("SELECT \"Group\".\"id\", \"Group\".name, Coalesce(sum(\"ExpenseParticipant\".amount),0) as balance, Coalesce(\"Expense\".currency, \"Group\".\"defaultCurrency\") as currency\nFROM \"GroupUser\"\nJOIN \"Group\" ON \"GroupUser\".\"groupId\" = \"Group\".id\nLEFT JOIN \"Expense\" ON \"Expense\".\"groupId\" = \"Group\".id\nLEFT JOIN \"ExpenseParticipant\" ON \"Expense\".id = \"ExpenseParticipant\".\"expenseId\"\nWHERE \"GroupUser\".\"userId\" = $1 AND \"deletedAt\" IS NULL AND (\"ExpenseParticipant\".\"userId\" = $1 OR \"Expense\".id is null)\nGROUP BY \"Group\".id, \"Group\".name, \"Expense\".currency\nORDER BY \"Group\".\"createdAt\" DESC, balance DESC")
