
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
"use strict"
exports.getAllBalancesForGroup = require("./getAllBalancesForGroup.js").getAllBalancesForGroup
exports.getGroupsWithBalances = require("./getGroupsWithBalances.js").getGroupsWithBalances
